title:             Egypt Shattered Order | Narrative adventure with factual history at its core | Orcinus Games
email:             dev@orsondewitt.com
description:       Narrative adventure with factual Ancient Egyptian history at its core
author:            Orcinus Games
#url:               "localhost:4000"
url:               "http://orsondewitt.github.io"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
subreddit: OrcinusGames
discord_invite: https://discord.gg/amMNE4x
steam_creator_page: https://store.steampowered.com/developer/orcinusgames/
youtube: https://www.youtube.com/channel/UCdod8Lkks-QqSjm0epIHv-A
email: dev@orsondewitt.com

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
