title:             Egypt Shattered Order - Interactive novel with factual history at its core | Orcinus Games
email:             dev@orsondewitt.com
description:       Interactive novel with factual Ancient Egyptian history at its core
author:            Orcinus Games
#url:               "localhost:4000"
url:               "http://orsondewitt.github.io/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
subreddit: OrcinusGames
discord_invite: https://discord.gg/amMNE4x

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
